services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app/backend/
      - ${DATASET_DIR:-./datasets}:/app/datasets/
    working_dir: /app
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: uvicorn backend:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --reload
